### ISSUE TITLE
Center plugin is breaking fluid layouts

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.js.cycle2#1]
This plugin should be removed, and this kind of problem should be resolved into CSS or local JS.

This plugin added globally is breaking my fluid layout adding a margin-top into active slide.

![screenshot from 2015-05-15 10 44 11](https://cloud.githubusercontent.com/assets/131209/7653893/83f9dff4-faef-11e4-910a-cfcb79e42d5d.png)

**Comment by hvelarde** [comment]
I think we must use a different approach here; I've seen that other packages on the **collective.js** name space they don't use the JS and CSS registries, they only register the directory to be used using ZCML; that way, we can still provide the plugin for people who want to use it.

@agnogueira @djowett comments? opinions?

**Comment by djowett** [comment]
@hvelarde I think you're right - the plugin should be either removed from jsregistry.xml or registered with `enabled="False"` (possibly the same for swipe plugin - as many people may have jquery mobile already installed).   The basic cycle2 JS should still be registered though, otherwise there's no point to this addon.

I tried looking for the other examples you mentioned... but couldn't find them.  However,  collective.js.angular seems to have a few different options in GS to cater for Plone 5 as well as Plone 4 (but I'm not skilled up in that yet)

**Comment by hvelarde** [comment]
@djowett here's an example: https://github.com/collective/collective.js.bootstrap/tree/master/collective/js/bootstrap

**Comment by rodfersou** [comment]
nice, so we can add all oficial cycle2 plugins into this package?

**Comment by djowett** [comment]
@rodfersou if not enabled, then I guess so, as they are pretty light (1 - 2Kb).

Does anyone else depend on this addon currently?

By the way, your problem isn't that Center plugin is enabled - it's that your template is using the options - I'd suggest fixing or overriding the template:

> The center plugin provides the options data-cycle-center-horz and data-cycle-center-vert, both of which accept booleans and **default to false**. Set one or both options to true to enable auto-centering of your slides. 
> (from http://jquery.malsup.com/cycle2/demo/center.php, emphasis mine)

**Comment by hvelarde** [comment]
@rodfersou we will also have to fix https://github.com/simplesconsultoria/sc.photogallery

**Comment by rodfersou** [comment]
@djowett no, the main problem is the center plugin.. it is adding a wrong margin-top into cycle2 container.

But I didn't commit that problem, I took out the responsive stuff into last commit waiting the possibility to take off center plugin

**Comment by djowett** [comment]
@rodfersou do you not have "data-cycle-center-vert" in that template?

**Comment by djowett** [comment]
@rodfersou @hvelarde I don't think we should be [removing the whole profile](https://community.plone.org/t/upgrade-step-to-remove-profile/668) - just the registration of the centre plugin.

You don't have to run the profile if you don't want it, but the JS & CSS registries are useful ways to manage these resources & we should encourage their use on Plone 4.

In any case, removing the profile here as a way to fix Centering in another product is using a sledgehammer to crack a nut.  Just remove the [following line in galleria.pt](https://github.com/collective/collective.nitf/blob/issue_116/src/collective/nitf/browser/templates/galleria.pt#L46) and you should be sorted:

> data-cycle-center-vert="true"

**Comment by rodfersou** [comment]
take a look at this pull request #2

**Comment by rodfersou** [comment]
I'm working on the other addons dependencies now

**Comment by djowett** [comment]
@rodfersou I'm still -1

**Comment by rodfersou** [comment]
@djowett thought that we agreed that this kind of package was meant just to add resources to be used into some addons.. like c.js.bootstrap ... it is referenced by the addon that need this resource.

Also, thank you about the `data-cycle-center-vert="true"`  I will take it out of the template later.

**Comment by rodfersou** [comment]
@djowett did you see that covertile buildout is not working when add a new plone site? I opened an issue about it: https://github.com/collective/covertile.cycle2/issues/8
